/*
 * PokeMisteryRL â€” TESTI DEL GIOCO
 *
 * Questo Ã¨ l'unico file da modificare per cambiare le scritte mostrate dal
 * core. A sinistra inserisci il testo attuale, a destra quello desiderato.
 * Le chiavi non presenti restano in italiano originale.
 */
(function(){
  "use strict";

  const REPLACEMENTS = {
    "#6890F0": "#6890F0",
    "#7038F8": "#7038F8",
    "#78C850": "#78C850",
    "#98D8D8": "#98D8D8",
    "#A040A0": "#A040A0",
    "#A890F0": "#A890F0",
    "#A8B820": "#A8B820",
    "#B8A038": "#B8A038",
    "#B8B8D0": "#B8B8D0",
    "#battleFinal #battleS2HpBar": "#battleFinal #battleS2HpBar",
    "#battleFinal #battleS2HpTxt": "#battleFinal #battleS2HpTxt",
    "#battleFinal .bf-field": "#battleFinal .bf-field",
    "#battleFinal .bf-sprite.enemy": "#battleFinal .bf-sprite.enemy",
    "#battleFinal .bf-sprite.is-attacking, #bottomCampagna .is-attacking": "#battleFinal .bf-sprite.is-attacking, #bottomCampagna .is-attacking",
    "#battleFinal .bf-sprite.s2": "#battleFinal .bf-sprite.s2",
    "#bottomContainer .b8-right": "#bottomContainer .b8-right",
    "#bottomContainer [data-team-index],#bottomContainer .team-slot": "#bottomContainer [data-team-index],#bottomContainer .team-slot",
    "#bottomContainer button": "#bottomContainer button",
    "#C03028": "#C03028",
    "#d2d2bdff": "#d2d2bdff",
    "#E0C068": "#E0C068",
    "#EE99AC": "#EE99AC",
    "#F08030": "#F08030",
    "#F85888": "#F85888",
    "#F8D030": "#F8D030",
    "#modal,#pokePreview,.modal,[role=\u0027dialog\u0027]": "#modal,#pokePreview,.modal,[role=\u0027dialog\u0027]",
    "#quickItemSlots [data-quick-item-slot]": "#quickItemSlots [data-quick-item-slot]",
    "#starter2Slot": "#starter2Slot",
    "(pokemon.tipi || []).includes(type)); return `": "(pokemon.tipi || []).includes(type)); return `",
    "(roll -= entry.weight)": "(roll -= entry.weight)",
    ") : `\u003cp class=": ") : `\u003cp class=",
    ") : `\u003csmall class=": ") : `\u003csmall class=",
    ")\" onclick=\"PokeMisteryRL.UI.openTest2BackpackItemInfo(": ")\" onclick=\"PokeMisteryRL.UI.openTest2BackpackItemInfo(",
    ").join(": ").join(",
    ").toLowerCase() +": ").toLowerCase() +",
    ").toLowerCase() ===": ").toLowerCase() ===",
    ").toLowerCase() === String(speciesName ||": ").toLowerCase() === String(speciesName ||",
    ").toLowerCase() === String(type ||": ").toLowerCase() === String(type ||",
    ").toLowerCase()) \u0026\u0026 ![": ").toLowerCase()) \u0026\u0026 ![",
    ").trim().toLowerCase() ===": ").trim().toLowerCase() ===",
    ").trim().toLowerCase(); if(!key) return": ").trim().toLowerCase(); if(!key) return",
    ").trim().toLowerCase()] || String(type ||": ").trim().toLowerCase()] || String(type ||",
    "); return `\u003cdiv class=": "); return `\u003cdiv class=",
    ", icon:item.icon ||": ", icon:item.icon ||",
    ", icon:item.icon || icons[item.id] ||": ", icon:item.icon || icons[item.id] ||",
    ", icon:removed.icon ||": ", icon:removed.icon ||",
    ",immagine:": ",immagine:",
    ",rect.height); svg.setAttribute(": ",rect.height); svg.setAttribute(",
    ",rect.width); svg.setAttribute(": ",rect.width); svg.setAttribute(",
    ",typing:": ",typing:",
    ": `\u003cbutton class=": ": `\u003cbutton class=",
    ": `\u003cbutton type=": ": `\u003cbutton type=",
    ": `\u003cimg src=": ": `\u003cimg src=",
    ": index === 1 ?": ": index === 1 ?",
    "; const rect=svg.getBoundingClientRect(); svg.setAttribute(": "; const rect=svg.getBoundingClientRect(); svg.setAttribute(",
    "; map.innerHTML =": "; map.innerHTML =",
    "[data-quick-item-slot]": "[data-quick-item-slot]",
    "[STARTER]": "[STARTER]",
    "__campaignBurned": "__campaignBurned",
    "__campaignFrozenTurns": "__campaignFrozenTurns",
    "__campaignPoisoned": "__campaignPoisoned",
    "__campaignSlow": "__campaignSlow",
    "__campaignStunTurns": "__campaignStunTurns",
    "` : page === \"nodes\" ? `": "` : page === \"nodes\" ? `",
    "`).join(\"\") : `": "`).join(\"\") : `",
    "`).join(\"\") || \"": "`).join(\"\") || \"",
    "`).join(\"\") || `": "`).join(\"\") || `",
    "|| String(activeSkill?.categoria ||": "|| String(activeSkill?.categoria ||",
    "|| String(enemySkill?.categoria ||": "|| String(enemySkill?.categoria ||",
    "|| String(skill?.categoria ||": "|| String(skill?.categoria ||",
    "+ PARTNER": "+ PARTNER",
    "+10% danno": "+10% danno",
    "+10% danno Fuoco": "+10% danno Fuoco",
    "+10% evasione": "+10% evasione",
    "+15% danni ai rallentati": "+15% danni ai rallentati",
    "+2 LIVELLI SKILL": "+2 LIVELLI SKILL",
    "+20% danno": "+20% danno",
    "+20% danno e bruciatura": "+20% danno e bruciatura",
    "+25% evasione": "+25% evasione",
    "+25% sotto 50% HP": "+25% sotto 50% HP",
    "+5 livelli": "+5 livelli",
    "+60% sotto 50% HP": "+60% sotto 50% HP",
    "= 0 \u0026\u0026 saved": "= 0 \u0026\u0026 saved",
    "= 250 \u0026\u0026 Number(pokemon.bst)": "= 250 \u0026\u0026 Number(pokemon.bst)",
    "=2? \"SUPEREFFICACE\" : m": "=2? \"SUPEREFFICACE\" : m",
    "\u003e` : `\u003cspan class=": "\u003e` : `\u003cspan class=",
    "\u003e`).join(": "\u003e`).join(",
    "\u003e\u003cb id=": "\u003e\u003cb id=",
    "\u003e\u003cb style=": "\u003e\u003cb style=",
    "\u003e\u003cbutton type=": "\u003e\u003cbutton type=",
    "\u003e\u003cdiv class=": "\u003e\u003cdiv class=",
    "\u003e\u003cimg class=": "\u003e\u003cimg class=",
    "\u003e\u003cimg src=": "\u003e\u003cimg src=",
    "\u003e\u003cspan class=": "\u003e\u003cspan class=",
    "0 \u0026\u0026 a.level": "0 \u0026\u0026 a.level",
    "0 \u0026\u0026 beetleCloneSprite ? `": "0 \u0026\u0026 beetleCloneSprite ? `",
    "0 \u0026\u0026 id": "0 \u0026\u0026 id",
    "0 \u0026\u0026 Math.random()": "0 \u0026\u0026 Math.random()",
    "0 \u0026\u0026 PokeMisteryRL.Campaigns?.level?.(\"roccia\") \u0026\u0026 Math.random()": "0 \u0026\u0026 PokeMisteryRL.Campaigns?.level?.(\"roccia\") \u0026\u0026 Math.random()",
    "-10% danni": "-10% danni",
    "-15% danni e riflesso": "-15% danni e riflesso",
    "15% doppio colpo": "15% doppio colpo",
    "2 oggetti curativi": "2 oggetti curativi",
    "-20% danni e scudo": "-20% danni e scudo",
    "25% al nemico dietro": "25% al nemico dietro",
    "30% doppio colpo": "30% doppio colpo",
    "50 ðŸ’°": "50 ðŸ’°",
    "50% al nemico dietro": "50% al nemico dietro",
    "-8% danni": "-8% danni",
    "Ã—": "Ã—",
    "A 0 PS un PokÃ©mon Ã¨ KO: non agisce finchÃ© non viene curato.": "A 0 PS un PokÃ©mon Ã¨ KO: non agisce finchÃ© non viene curato.",
    "â—ˆ": "â—ˆ",
    "Ã¨ bloccato piÃ¹ avanti.": "Ã¨ bloccato piÃ¹ avanti.",
    "Ã¨ bloccato piÃ¹ avanti. Vuoi attraversare il mini-dungeon per aiutarlo?": "Ã¨ bloccato piÃ¹ avanti. Vuoi attraversare il mini-dungeon per aiutarlo?",
    "â˜": "â˜",
    "â˜  VELENO": "â˜  VELENO",
    "â˜°": "â˜°",
    "â˜¾": "â˜¾",
    "â—€": "â—€",
    "â€“": "â€“",
    "â€”": "â€”",
    "â€¢": "â€¢",
    "â€º": "â€º",
    "â¬‡ï¸": "â¬‡ï¸",
    "â¬Ÿ": "â¬Ÿ",
    "â–¶": "â–¶",
    "Â·": "Â·",
    "Â· +50% PS; sfida o cambio tipo skill.": "Â· +50% PS; sfida o cambio tipo skill.",
    "Â· Bonus, scelta o imprevisto.": "Â· Bonus, scelta o imprevisto.",
    "Â· Chiude il piano.": "Â· Chiude il piano.",
    "Â· Compra oggetti.": "Â· Compra oggetti.",
    "Â· Sfida per potenziare una skill.": "Â· Sfida per potenziare una skill.",
    "Â· Vinci per denaro ed esperienza.": "Â· Vinci per denaro ed esperienza.",
    "â—†": "â—†",
    "â†’": "â†’",
    "â†”": "â†”",
    "â†»": "â†»",
    "â†» REROLL": "â†» REROLL",
    "â† INDIETRO": "â† INDIETRO",
    "â† TORNA AGLI SCAFFALI": "â† TORNA AGLI SCAFFALI",
    "â† TORNA ALLO ZAINO": "â† TORNA ALLO ZAINO",
    "â† ZAINO": "â† ZAINO",
    "â—‰": "â—‰",
    "â—": "â—",
    "â­ Equipaggia come Starter2": "â­ Equipaggia come Starter2",
    "â­ Imposta compagno": "â­ Imposta compagno",
    "â— PERCORSO BLOCCATO": "â— PERCORSO BLOCCATO",
    "â­ SCEGLI I COMPAGNI": "â­ SCEGLI I COMPAGNI",
    "â­ SCEGLI LO STARTER": "â­ SCEGLI LO STARTER",
    "â­ SQUADRA COMPLETA": "â­ SQUADRA COMPLETA",
    "â“": "â“",
    "â“ PASSAGGIO NASCOSTO": "â“ PASSAGGIO NASCOSTO",
    "â“ SOCCORSO": "â“ SOCCORSO",
    "â„": "â„",
    "â„ GELO": "â„ GELO",
    "â¤ï¸": "â¤ï¸",
    "â–¼": "â–¼",
    "â–²": "â–²",
    "absolute": "absolute",
    "acceptShelterChallenge()": "acceptShelterChallenge()",
    "acceptSkillChallenge()": "acceptSkillChallenge()",
    "ACCETTA": "ACCETTA",
    "Accetti la sfida?": "Accetti la sfida?",
    "acciaio": "acciaio",
    "acqua": "acqua",
    "Acqua Fresca": "Acqua Fresca",
    "Acqua Magica": "Acqua Magica",
    "acqua_fresca": "acqua_fresca",
    "acqua_magica": "acqua_magica",
    "active": "active",
    "adventure-shell": "adventure-shell",
    "Affronta il PokÃ©mon del Dojo e conquista un oggetto potenziatore.": "Affronta il PokÃ©mon del Dojo e conquista un oggetto potenziatore.",
    "alt=": "alt=",
    "amulet-coin": "amulet-coin",
    "amuleto": "amuleto",
    "Amuleto": "Amuleto",
    "ANNULLA": "ANNULLA",
    "âœ¦": "âœ¦",
    "âœ¦ GAME OVER": "âœ¦ GAME OVER",
    "âœ¦ VITTORIA": "âœ¦ VITTORIA",
    "âœ¨ PASSAGGIO LIBERO": "âœ¨ PASSAGGIO LIBERO",
    "âœ¨ PREMIO OTTENUTO": "âœ¨ PREMIO OTTENUTO",
    "âœ¨ RECLUTAMENTO": "âœ¨ RECLUTAMENTO",
    "âœ¨ SOCCORSO RIUSCITO": "âœ¨ SOCCORSO RIUSCITO",
    "âœ¨ Vincendo, scegli un compagno che ottiene": "âœ¨ Vincendo, scegli un compagno che ottiene",
    "âœ¿": "âœ¿",
    "âŒ˜": "âŒ˜",
    "âœ“ ACCETTA": "âœ“ ACCETTA",
    "âœ“ AIUTA": "âœ“ AIUTA",
    "âœ“ ANDIAMO": "âœ“ ANDIAMO",
    "âŒ› CARICAMENTO POKÃ‰API": "âŒ› CARICAMENTO POKÃ‰API",
    "âœ§": "âœ§",
    "âœ… DB_ITEMS caricato:": "âœ… DB_ITEMS caricato:",
    "âœ•": "âœ•",
    "âœº": "âœº",
    "âœŠ": "âœŠ",
    "Applica SPD â†“": "Applica SPD â†“",
    "Applica veleno": "Applica veleno",
    "Apri o chiudi zaino": "Apri o chiudi zaino",
    "Apri tab": "Apri tab",
    "APRI ZAINO": "APRI ZAINO",
    "Arbok": "Arbok",
    "Arcanine": "Arcanine",
    "arena usano l": "arena usano l",
    "argentovivo": "argentovivo",
    "Argentovivo": "Argentovivo",
    "aria-hidden": "aria-hidden",
    "aria-label=": "aria-label=",
    "âš ï¸ BOSS IN ARRIVO": "âš ï¸ BOSS IN ARRIVO",
    "âš¡": "âš¡",
    "âš¡ ELETTRO": "âš¡ ELETTRO",
    "âš¡ PokeMisteryRL": "âš¡ PokeMisteryRL",
    "âš¡ Vittoria: una riserva ottiene": "âš¡ Vittoria: una riserva ottiene",
    "âš”": "âš”",
    "âš” ACCETTA": "âš” ACCETTA",
    "âš” ACCETTA SFIDA": "âš” ACCETTA SFIDA",
    "âš” ATTENDI L\u0027ESITO DELLA SFIDA": "âš” ATTENDI L\u0027ESITO DELLA SFIDA",
    "âš” INIZIA LA SFIDA": "âš” INIZIA LA SFIDA",
    "âš” VS": "âš” VS",
    "âš”ï¸": "âš”ï¸",
    "âš”ï¸ ACCETTA LA PROVA": "âš”ï¸ ACCETTA LA PROVA",
    "âš”ï¸ ACCETTA LA SFIDA": "âš”ï¸ ACCETTA LA SFIDA",
    "ASSEGNA OGGETTO": "ASSEGNA OGGETTO",
    "assorbisfera": "assorbisfera",
    "Assorbisfera (Life Orb)": "Assorbisfera (Life Orb)",
    "âš™": "âš™",
    "ATK": "ATK",
    "atk": "atk",
    "ATK e ATT. SP Ã—2 attivi": "ATK e ATT. SP Ã—2 attivi",
    "atkVal": "atkVal",
    "ATT +2 livelli": "ATT +2 livelli",
    "ATT. SP": "ATT. SP",
    "ATTACCO": "ATTACCO",
    "attacker": "attacker",
    "Attendi l\u0027esito del combattimento.": "Attendi l\u0027esito del combattimento.",
    "â™¥": "â™¥",
    "â™¥ RIFUGIO": "â™¥ RIFUGIO",
    "â™¥ SFIDA DEL RIFUGIO": "â™¥ SFIDA DEL RIFUGIO",
    "â™œ": "â™œ",
    "auto": "auto",
    "available": "available",
    "AVANTI": "AVANTI",
    "avanzi": "avanzi",
    "Avanzi (Leftovers)": "Avanzi (Leftovers)",
    "AVVERSARI": "AVVERSARI",
    "âž¡ï¸ Partner": "âž¡ï¸ Partner",
    "âž¡ï¸ Starter": "âž¡ï¸ Starter",
    "b8-bar-bg": "b8-bar-bg",
    "b8-bar-row": "b8-bar-row",
    "b8-bars": "b8-bars",
    "b8-center": "b8-center",
    "b8-center-main": "b8-center-main",
    "b8-fill hp": "b8-fill hp",
    "b8-icon": "b8-icon",
    "b8-inventory-panel center-inventory-panel": "b8-inventory-panel center-inventory-panel",
    "b8-inventory-section": "b8-inventory-section",
    "b8-left": "b8-left",
    "b8-lv": "b8-lv",
    "b8-money": "b8-money",
    "b8-money-icon": "b8-money-icon",
    "b8-name": "b8-name",
    "b8-pokemon-slot": "b8-pokemon-slot",
    "b8-quick-item empty": "b8-quick-item empty",
    "b8-quick-items": "b8-quick-items",
    "b8-right": "b8-right",
    "b8-right-main": "b8-right-main",
    "b8-s2-header": "b8-s2-header",
    "b8-s2-level": "b8-s2-level",
    "b8-s2-name": "b8-s2-name",
    "b8-s2-section": "b8-s2-section",
    "b8-stats": "b8-stats",
    "b8-team-header": "b8-team-header",
    "b8-team-image-wrap": "b8-team-image-wrap",
    "b8-team-viewer": "b8-team-viewer",
    "b8-team-viewer-level": "b8-team-viewer-level",
    "b8-team-viewer-name": "b8-team-viewer-name",
    "b8-top": "b8-top",
    "b8-typing": "b8-typing",
    "b8-typing b8-s2-typing": "b8-typing b8-s2-typing",
    "b8-value": "b8-value",
    "background-image": "background-image",
    "background-position": "background-position",
    "background-repeat": "background-repeat",
    "background-size": "background-size",
    "backpack-item-description-icon": "backpack-item-description-icon",
    "balanced": "balanced",
    "bar": "bar",
    "Barre vita": "Barre vita",
    "BATTAGLIA NON DISPONIBILE": "BATTAGLIA NON DISPONIBILE",
    "battleEnemyHpBar": "battleEnemyHpBar",
    "battleEnemyHpTxt": "battleEnemyHpTxt",
    "battleFinal": "battleFinal",
    "battle-reward-grid": "battle-reward-grid",
    "battleS1HpBar": "battleS1HpBar",
    "battleS1HpTxt": "battleS1HpTxt",
    "battleS2HpBar": "battleS2HpBar",
    "battleS2HpTxt": "battleS2HpTxt",
    "bazar": "bazar",
    "Beccaffilato": "Beccaffilato",
    "beccaffilato": "beccaffilato",
    "beforeend": "beforeend",
    "Bellsprout": "Bellsprout",
    "Bersagli": "Bersagli",
    "Bersagli e turni": "Bersagli e turni",
    "bf-beetle-clone": "bf-beetle-clone",
    "bf-empty-slot": "bf-empty-slot",
    "bf-enemy-hud": "bf-enemy-hud",
    "bf-enemy-squad": "bf-enemy-squad",
    "bf-field": "bf-field",
    "bf-fleeBox": "bf-fleeBox",
    "bf-formation-panel": "bf-formation-panel",
    "bf-hp-text": "bf-hp-text",
    "bf-log": "bf-log",
    "bf-logRow": "bf-logRow",
    "bf-name-row": "bf-name-row",
    "bf-player-bottom": "bf-player-bottom",
    "bf-player-hud": "bf-player-hud",
    "bf-player-squad": "bf-player-squad",
    "bf-sprite s2": "bf-sprite s2",
    "bf-sprite s2 empty": "bf-sprite s2 empty",
    "bf-statuses": "bf-statuses",
    "bf-top": "bf-top",
    "bf-turn-control": "bf-turn-control",
    "bf-versus": "bf-versus",
    "bip-empty": "bip-empty",
    "bip-head": "bip-head",
    "bip-list": "bip-list",
    "bip-row": "bip-row",
    "bip-title": "bip-title",
    "biscotto_lava": "biscotto_lava",
    "bitorzolello": "bitorzolello",
    "Bitorzolello (Rocky Helmet)": "Bitorzolello (Rocky Helmet)",
    "bits": "bits",
    "black-belt": "black-belt",
    "black-glasses": "black-glasses",
    "Blastoise": "Blastoise",
    "block": "block",
    "blog": "blog",
    "blue": "blue",
    "bonus": "bonus",
    "BONUS ATTIVO": "BONUS ATTIVO",
    "BONUS DELLA RUN": "BONUS DELLA RUN",
    "bosco": "bosco",
    "Bosco di Nebbia": "Bosco di Nebbia",
    "boss": "boss",
    "Boss": "Boss",
    "Boss sconfitto!": "Boss sconfitto!",
    "boss1": "boss1",
    "boss2": "boss2",
    "boss-prep-grid": "boss-prep-grid",
    "BOTTEGA DI KECLEON": "BOTTEGA DI KECLEON",
    "bottomCampagna": "bottomCampagna",
    "bottom-campagna": "bottom-campagna",
    "bottom-campagna test2-fight-bottom": "bottom-campagna test2-fight-bottom",
    "bottom-campagna-formation": "bottom-campagna-formation",
    "bottom-campagna-hp": "bottom-campagna-hp",
    "bottom-campagna-title": "bottom-campagna-title",
    "bottom-campagna-types": "bottom-campagna-types",
    "bottomContainer": "bottomContainer",
    "bottomInventoryPanel": "bottomInventoryPanel",
    "bottom-inventory-panel": "bottom-inventory-panel",
    "bottomPanel": "bottomPanel",
    "bottomRightPanel": "bottomRightPanel",
    "bottom-v8": "bottom-v8",
    "Braci Vive": "Braci Vive",
    "bruciatura": "bruciatura",
    "btn-flee": "btn-flee",
    "buio": "buio",
    "Bulbasaur": "Bulbasaur",
    "button": "button",
    "Cambia ordine squadra": "Cambia ordine squadra",
    "CAMBIO FORMAZIONE": "CAMBIO FORMAZIONE",
    "campagna": "campagna",
    "Campagna sperimentale": "Campagna sperimentale",
    "Campagna sperimentale.": "Campagna sperimentale.",
    "campagne": "campagne",
    "campaignTestBits": "campaignTestBits",
    "campaignTestBottom": "campaignTestBottom",
    "campaign-test-bottom": "campaign-test-bottom",
    "campaign-test-bottom-foot": "campaign-test-bottom-foot",
    "campaign-test-hp": "campaign-test-hp",
    "campaign-test-member empty": "campaign-test-member empty",
    "campaign-test-member-stats": "campaign-test-member-stats",
    "campaignTestParty": "campaignTestParty",
    "campaign-test-party": "campaign-test-party",
    "campaign-test-sprite-box": "campaign-test-sprite-box",
    "campaign-test-stats-box": "campaign-test-stats-box",
    "campaign-test-stat-title": "campaign-test-stat-title",
    "campeggio": "campeggio",
    "Caramella Rara": "Caramella Rara",
    "caramella_furia": "caramella_furia",
    "caramella_rara": "caramella_rara",
    "carbonella": "carbonella",
    "Carbonella": "Carbonella",
    "Carte raccolte": "Carte raccolte",
    "casteliacone": "casteliacone",
    "Catalogo PokeAPI non pronto": "Catalogo PokeAPI non pronto",
    "caterpie": "caterpie",
    "Cenere Sacra": "Cenere Sacra",
    "cenere_sacra": "cenere_sacra",
    "center": "center",
    "center adventure-event-victory": "center adventure-event-victory",
    "center backpack-item-description": "center backpack-item-description",
    "center battle-reward": "center battle-reward",
    "center battle-reward gameover-reward": "center battle-reward gameover-reward",
    "center boss-prep": "center boss-prep",
    "center dojo-challenge": "center dojo-challenge",
    "center evolution-modal": "center evolution-modal",
    "center evolution-result": "center evolution-result",
    "center floor-upgrade-modal": "center floor-upgrade-modal",
    "center floor-upgrade-modal collector-view": "center floor-upgrade-modal collector-view",
    "center guide-panel": "center guide-panel",
    "center guide-panel guide-category": "center guide-panel guide-category",
    "center guide-panel guide-home": "center guide-panel guide-home",
    "center hidden-passage-prompt hidden-passage-recruit": "center hidden-passage-prompt hidden-passage-recruit",
    "center home-menu": "center home-menu",
    "center quick-item-detail item-action-modal": "center quick-item-detail item-action-modal",
    "center recruitment-offer": "center recruitment-offer",
    "center run-victory": "center run-victory",
    "center s2-no-companion-modal": "center s2-no-companion-modal",
    "center shelter-challenge": "center shelter-challenge",
    "center shelter-node": "center shelter-node",
    "center shop-box shop-empty": "center shop-box shop-empty",
    "center shop-box shop-rework": "center shop-box shop-rework",
    "center shop-item-modal": "center shop-item-modal",
    "center skill-node": "center skill-node",
    "center skill-result-node": "center skill-result-node",
    "center starter-picker starting-s2-picker": "center starter-picker starting-s2-picker",
    "center test2-member-info": "center test2-member-info",
    "center test-backpack-modal": "center test-backpack-modal",
    "center victory-box": "center victory-box",
    "centerInventoryPanel": "centerInventoryPanel",
    "centerMainPanel": "centerMainPanel",
    "changeTeamPreview(1)": "changeTeamPreview(1)",
    "changeTeamPreview(-1)": "changeTeamPreview(-1)",
    "Chansey": "Chansey",
    "Chansey Ã¨ stata sconfitta!": "Chansey Ã¨ stata sconfitta!",
    "charcoal": "charcoal",
    "Charizard": "Charizard",
    "Charmander": "Charmander",
    "checkbox": "checkbox",
    "checked": "checked",
    "Chi vuoi sostituire?": "Chi vuoi sostituire?",
    "CHIUDI": "CHIUDI",
    "Chiudi": "Chiudi",
    "Chiudi zaino": "Chiudi zaino",
    "choose": "choose",
    "cinturanera": "cinturanera",
    "Cinturanera": "Cinturanera",
    "class": "class",
    "class=": "class=",
    "click": "click",
    "clone": "clone",
    "Clone Coleottero": "Clone Coleottero",
    "Clone verde 30% HP": "Clone verde 30% HP",
    "Clone verde 70% HP": "Clone verde 70% HP",
    "closeBottomInventory()": "closeBottomInventory()",
    "closeModal()": "closeModal()",
    "closeModal(); busy=0; PokeMisteryRL.UI.render();": "closeModal(); busy=0; PokeMisteryRL.UI.render();",
    "closeModal(); PokeMisteryRL.UI.render();": "closeModal(); PokeMisteryRL.UI.render();",
    "closePokeInfo()": "closePokeInfo()",
    "closeTeamPreview();busy=0;PokeMisteryRL.UI.render();": "closeTeamPreview();busy=0;PokeMisteryRL.UI.render();",
    "Cloyster": "Cloyster",
    "code-attack": "code-attack",
    "code-type-accent": "code-type-accent",
    "code-type-attack": "code-type-attack",
    "code-type-core": "code-type-core",
    "coleottero": "coleottero",
    "Colpo di Grazia": "Colpo di Grazia",
    "Colpo Jolly": "Colpo Jolly",
    "Comandi run": "Comandi run",
    "combat": "combat",
    "Combattimento": "Combattimento",
    "Come funziona un turno": "Come funziona un turno",
    "COMP. 1": "COMP. 1",
    "COMP. 2": "COMP. 2",
    "comune": "comune",
    "cono_castelia": "cono_castelia",
    "Conostropoli": "Conostropoli",
    "contain": "contain",
    "contents": "contents",
    "CONTINUA": "CONTINUA",
    "copy": "copy",
    "Corazza di Pietra": "Corazza di Pietra",
    "CORE 1 ready:": "CORE 1 ready:",
    "CORE 2 ready:": "CORE 2 ready:",
    "Cosa vuoi fare?": "Cosa vuoi fare?",
    "counterStarter": "counterStarter",
    "Courier New": "Courier New",
    "cover": "cover",
    "crescita": "crescita",
    "crit": "crit",
    "CRIT!": "CRIT!",
    "cucchiaiorto": "cucchiaiorto",
    "Cucchiaiorto": "Cucchiaiorto",
    "cura": "cura",
    "Cura 100 PS.": "Cura 100 PS.",
    "Cura 120 PS.": "Cura 120 PS.",
    "Cura 2% HP": "Cura 2% HP",
    "Cura 20 PS.": "Cura 20 PS.",
    "Cura 30 HP.": "Cura 30 HP.",
    "Cura 4% HP": "Cura 4% HP",
    "Cura 50 PS.": "Cura 50 PS.",
    "Cura 60 HP.": "Cura 60 HP.",
    "Cura 70 PS.": "Cura 70 PS.",
    "Cura 8% HP": "Cura 8% HP",
    "Cura completamente gli HP e gli status.": "Cura completamente gli HP e gli status.",
    "Cura completamente gli HP.": "Cura completamente gli HP.",
    "Cura e riposo": "Cura e riposo",
    "Cura gli status.": "Cura gli status.",
    "Cure +20%": "Cure +20%",
    "Cure +40%": "Cure +40%",
    "current": "current",
    "danger": "danger",
    "Danno mosse FOLLETTO Ã—1,20.": "Danno mosse FOLLETTO Ã—1,20.",
    "data:": "data:",
    "data-battle-enemy=": "data-battle-enemy=",
    "data-battle-player=": "data-battle-player=",
    "data-quick-item-slot": "data-quick-item-slot",
    "data-s2-index": "data-s2-index",
    "dead": "dead",
    "declineHiddenPassage()": "declineHiddenPassage()",
    "DEF": "DEF",
    "defVal": "defVal",
    "degli HP all\u0027arrivo.": "degli HP all\u0027arrivo.",
    "DENARO": "DENARO",
    "Denaro vinto Ã—2": "Denaro vinto Ã—2",
    "Dente di Drago": "Dente di Drago",
    "dente_di_drago": "dente_di_drago",
    "DETTAGLI OGGETTO": "DETTAGLI OGGETTO",
    "Devi prima ottenere questo oggetto nell\u0027inventario.": "Devi prima ottenere questo oggetto nell\u0027inventario.",
    "Dewgong": "Dewgong",
    "dialog": "dialog",
    "dif": "dif",
    "DIF": "DIF",
    "DIF e DIF. SP +50%": "DIF e DIF. SP +50%",
    "DIF e DIF. SP +50% se puÃ² evolversi": "DIF e DIF. SP +50% se puÃ² evolversi",
    "DIF. SP": "DIF. SP",
    "DIFESA": "DIFESA",
    "disabled": "disabled",
    "discardedStartersOrMoltres": "discardedStartersOrMoltres",
    "display": "display",
    "display:flex;gap:6px;flex-wrap:wrap;margin-top:8px": "display:flex;gap:6px;flex-wrap:wrap;margin-top:8px",
    "display:flex;gap:6px;margin-top:8px;flex-wrap:wrap": "display:flex;gap:6px;margin-top:8px;flex-wrap:wrap",
    "display:none": "display:none",
    "dittoMew": "dittoMew",
    "div": "div",
    "DIVENTA": "DIVENTA",
    "DMG [BUG] Ã—1.20.": "DMG [BUG] Ã—1.20.",
    "DMG [DARK] Ã—1.20.": "DMG [DARK] Ã—1.20.",
    "DMG [DRAGON] Ã—1.20.": "DMG [DRAGON] Ã—1.20.",
    "DMG [ELECTRIC] Ã—1.20.": "DMG [ELECTRIC] Ã—1.20.",
    "DMG [FIGHTING] Ã—1.20.": "DMG [FIGHTING] Ã—1.20.",
    "DMG [FIRE] Ã—1.20.": "DMG [FIRE] Ã—1.20.",
    "DMG [FLYING] Ã—1.20.": "DMG [FLYING] Ã—1.20.",
    "DMG [GHOST] Ã—1.20.": "DMG [GHOST] Ã—1.20.",
    "DMG [GRASS] Ã—1.20.": "DMG [GRASS] Ã—1.20.",
    "DMG [GROUND] Ã—1.20.": "DMG [GROUND] Ã—1.20.",
    "DMG [ICE] Ã—1.20.": "DMG [ICE] Ã—1.20.",
    "DMG [NORMAL] Ã—1.20.": "DMG [NORMAL] Ã—1.20.",
    "DMG [POISON] Ã—1.20.": "DMG [POISON] Ã—1.20.",
    "DMG [PSYCHIC] Ã—1.20.": "DMG [PSYCHIC] Ã—1.20.",
    "DMG [ROCK] Ã—1.20.": "DMG [ROCK] Ã—1.20.",
    "DMG [STEEL] Ã—1.20.": "DMG [STEEL] Ã—1.20.",
    "DMG [WATER] Ã—1.20.": "DMG [WATER] Ã—1.20.",
    "Dojo": "Dojo",
    "dojo": "dojo",
    "dojo-actions": "dojo-actions",
    "dojo-challenge-head": "dojo-challenge-head",
    "dojo-opponent": "dojo-opponent",
    "dojo-reward": "dojo-reward",
    "Dolce Chateau": "Dolce Chateau",
    "DOMContentLoaded": "DOMContentLoaded",
    "done": "done",
    "Dopo superefficace: ATK e ATT. SP Ã—2": "Dopo superefficace: ATK e ATT. SP Ã—2",
    "Dopo un colpo superefficace: Attacco +2 livelli.": "Dopo un colpo superefficace: Attacco +2 livelli.",
    "dps": "dps",
    "draggable=": "draggable=",
    "drago": "drago",
    "dragon-fang": "dragon-fang",
    "ðŸ‘¹": "ðŸ‘¹",
    "ðŸ—‘ï¸ Rilascia": "ðŸ—‘ï¸ Rilascia",
    "ðŸ’¨": "ðŸ’¨",
    "ðŸ’§": "ðŸ’§",
    "ðŸ’°": "ðŸ’°",
    "ðŸ’Ž": "ðŸ’Ž",
    "ðŸ“ˆ": "ðŸ“ˆ",
    "ðŸ“¦": "ðŸ“¦",
    "ðŸ“¿": "ðŸ“¿",
    "ðŸ”´": "ðŸ”´",
    "ðŸ”¥": "ðŸ”¥",
    "ðŸ”¥ BRUCIA": "ðŸ”¥ BRUCIA",
    "ðŸ›¡ï¸": "ðŸ›¡ï¸",
    "ðŸ›’ NEGOZIO": "ðŸ›’ NEGOZIO",
    "ðŸ¥‹": "ðŸ¥‹",
    "ðŸ¥‹ DOJO": "ðŸ¥‹ DOJO",
    "ðŸ¥‹ PREMIO DEL DOJO": "ðŸ¥‹ PREMIO DEL DOJO",
    "ðŸ¥‹ RICHIESTA DI SFIDA": "ðŸ¥‹ RICHIESTA DI SFIDA",
    "ðŸ¥‹ SFIDA DEL DOJO": "ðŸ¥‹ SFIDA DEL DOJO",
    "ðŸ¥š": "ðŸ¥š",
    "ðŸ§© TEST2": "ðŸ§© TEST2",
    "ðŸ–": "ðŸ–",
    "ðŸ": "ðŸ",
    "ðŸ RIFUGIO": "ðŸ RIFUGIO",
    "ðŸ±": "ðŸ±",
    "ðŸ¬": "ðŸ¬",
    "ðŸ† AVVENTURA COMPLETATA": "ðŸ† AVVENTURA COMPLETATA",
    "ðŸ† PREMIO Â· OGGETTO TIPO": "ðŸ† PREMIO Â· OGGETTO TIPO",
    "ðŸª": "ðŸª",
    "ðŸª NEGOZIO": "ðŸª NEGOZIO",
    "ðŸƒ": "ðŸƒ",
    "ðŸª–": "ðŸª–",
    "ðŸª½": "ðŸª½",
    "ðŸŽ’": "ðŸŽ’",
    "ðŸŽ’ INVENTARIO": "ðŸŽ’ INVENTARIO",
    "ðŸŽ’ ZAINO": "ðŸŽ’ ZAINO",
    "e": "e",
    "Effetto attivo": "Effetto attivo",
    "EFFETTO ATTIVO": "EFFETTO ATTIVO",
    "Ehi! Quello Ã¨ mio!": "Ehi! Quello Ã¨ mio!",
    "electricPlantBoss": "electricPlantBoss",
    "Electrode": "Electrode",
    "elettro": "elettro",
    "empty": "empty",
    "enemy": "enemy",
    "enemy-0": "enemy-0",
    "enemy2": "enemy2",
    "enterHiddenPassage()": "enterHiddenPassage()",
    "ENTRA NEL DOJO": "ENTRA NEL DOJO",
    "epica": "epica",
    "EQUIP": "EQUIP",
    "EQUIPAGGIA": "EQUIPAGGIA",
    "EQUIPAGGIA A": "EQUIPAGGIA A",
    "EQUIPAGGIABILE": "EQUIPAGGIABILE",
    "EQUIPAGGIABILI": "EQUIPAGGIABILI",
    "EQUIPAGGIAMENTI Â· TRASCINA O TOCCA": "EQUIPAGGIAMENTI Â· TRASCINA O TOCCA",
    "EQUIPAGGIAMENTO": "EQUIPAGGIAMENTO",
    "EQUIPAGGIAMENTO ATTIVO": "EQUIPAGGIAMENTO ATTIVO",
    "equipHeldItem": "equipHeldItem",
    "equipment": "equipment",
    "equipment-icon": "equipment-icon",
    "equipment-image": "equipment-image",
    "equipment-row": "equipment-row",
    "erba": "erba",
    "Erba Rivitalizzante": "Erba Rivitalizzante",
    "erba_rivitalizzante": "erba_rivitalizzante",
    "error": "error",
    "ERRORE DURANTE LA RUN": "ERRORE DURANTE LA RUN",
    "ERRORE JAVASCRIPT": "ERRORE JAVASCRIPT",
    "Escape": "Escape",
    "ESCI": "ESCI",
    "ESCI DAL NEGOZIO": "ESCI DAL NEGOZIO",
    "Esci dal negozio": "Esci dal negozio",
    "EVA": "EVA",
    "evade": "evade",
    "evasione": "evasione",
    "event": "event",
    "event-item-reward": "event-item-reward",
    "eventLog": "eventLog",
    "Evento": "Evento",
    "eviolite": "eviolite",
    "evolcondensa": "evolcondensa",
    "Evolcondensa (Eviolite)": "Evolcondensa (Eviolite)",
    "evolution-arrow": "evolution-arrow",
    "evolution-caption": "evolution-caption",
    "evolution-confirm": "evolution-confirm",
    "evolution-flash": "evolution-flash",
    "evolution-form evolution-from": "evolution-form evolution-from",
    "evolution-form evolution-to": "evolution-form evolution-to",
    "evolution-kicker": "evolution-kicker",
    "evolution-stage": "evolution-stage",
    "EVOLUZIONE COMPLETATA": "EVOLUZIONE COMPLETATA",
    "EVOLUZIONE DISPONIBILE": "EVOLUZIONE DISPONIBILE",
    "EVOLUZIONE!": "EVOLUZIONE!",
    "Fa perdere il turno": "Fa perdere il turno",
    "fairy-feather": "fairy-feather",
    "Fango Frenante": "Fango Frenante",
    "fatal": "fatal",
    "Fearow": "Fearow",
    "Fight": "Fight",
    "fight": "fight",
    "fight-acqua": "fight-acqua",
    "fight-bosco": "fight-bosco",
    "fight-grotta": "fight-grotta",
    "fight-torre": "fight-torre",
    "filled": "filled",
    "FINE PIANO": "FINE PIANO",
    "Fiocco Rosa": "Fiocco Rosa",
    "fiocco_rosa": "fiocco_rosa",
    "fisica": "fisica",
    "flee()": "flee()",
    "flex": "flex",
    "floor-collector": "floor-collector",
    "floor-upgrade-cards": "floor-upgrade-cards",
    "folletto": "folletto",
    "font-size:11px;opacity:.6": "font-size:11px;opacity:.6",
    "font-size:11px;opacity:.6;margin:0 0 8px": "font-size:11px;opacity:.6;margin:0 0 8px",
    "formation": "formation",
    "FORMAZIONE": "FORMAZIONE",
    "Formazione": "Formazione",
    "Formazione squadra": "Formazione squadra",
    "free": "free",
    "fresh-water": "fresh-water",
    "Fuga": "Fuga",
    "Fuga garantita dagli incontri": "Fuga garantita dagli incontri",
    "full-restore": "full-restore",
    "function": "function",
    "fuoco": "fuoco",
    "FUORI LOTTA": "FUORI LOTTA",
    "--fx-end": "--fx-end",
    "--fx-start": "--fx-start",
    "--fx-start-x": "--fx-start-x",
    "--fx-start-y": "--fx-start-y",
    "--fx-target-x": "--fx-target-x",
    "--fx-target-y": "--fx-target-y",
    "game": "game",
    "gameBox": "gameBox",
    "gelo": "gelo",
    "gelomai": "gelomai",
    "Gelomai": "Gelomai",
    "ghiaccio": "ghiaccio",
    "Giardino dei Veleni": "Giardino dei Veleni",
    "Gli oggetti rimasti sono gratis.": "Gli oggetti rimasti sono gratis.",
    "Gloom": "Gloom",
    "Golbat": "Golbat",
    "Goldeen": "Goldeen",
    "Golduck": "Golduck",
    "goMenu()": "goMenu()",
    "GRATIS": "GRATIS",
    "green": "green",
    "Growlithe": "Growlithe",
    "Guardia Ferrea": "Guardia Ferrea",
    "Guardiano del percorso": "Guardiano del percorso",
    "GUIDA": "GUIDA",
    "guide": "guide",
    "guide-allies": "guide-allies",
    "guide-back": "guide-back",
    "guide-category-list": "guide-category-list",
    "guide-enemies": "guide-enemies",
    "guide-page-list": "guide-page-list",
    "guide-priority": "guide-priority",
    "guide-priority guide-node-list": "guide-priority guide-node-list",
    "guide-target-visual": "guide-target-visual",
    "Gyarados": "Gyarados",
    "h2": "h2",
    "Hai conquistato Kanto!": "Hai conquistato Kanto!",
    "Hai ignorato il passaggio nascosto.": "Hai ignorato il passaggio nascosto.",
    "Hai lasciato il Rifugio.": "Hai lasciato il Rifugio.",
    "Hai pagato il branco e prosegui.": "Hai pagato il branco e prosegui.",
    "Hai ricevuto": "Hai ricevuto",
    "Hai rinunciato alla sfida di Chansey.": "Hai rinunciato alla sfida di Chansey.",
    "Hai sconfitto il branco": "Hai sconfitto il branco",
    "hard-stone": "hard-stone",
    "heal": "heal",
    "health": "health",
    "held-item-badge": "held-item-badge",
    "hidden": "hidden",
    "hidden-recruit": "hidden-recruit",
    "hit": "hit",
    "HOME": "HOME",
    "homeActions": "homeActions",
    "Horsea": "Horsea",
    "hp": "hp",
    "HP": "HP",
    "HP 0/0": "HP 0/0",
    "hpFillSide": "hpFillSide",
    "hpTextSide": "hpTextSide",
    "http": "http",
    "hyper-potion": "hyper-potion",
    "I tuoi PokÃ©mon": "I tuoi PokÃ©mon",
    "Il combattimento Ã¨ in corsoâ€¦": "Il combattimento Ã¨ in corsoâ€¦",
    "Il database oggetti non Ã¨ ancora disponibile.": "Il database oggetti non Ã¨ ancora disponibile.",
    "Il negozio Ã¨ vuoto.": "Il negozio Ã¨ vuoto.",
    "Il nuovo Attacco Ã¨ nella tab del PokÃ©mon.": "Il nuovo Attacco Ã¨ nella tab del PokÃ©mon.",
    "Il nuovo PWR Ã¨ mostrato direttamente nella tab della mossa.": "Il nuovo PWR Ã¨ mostrato direttamente nella tab della mossa.",
    "Il passaggio Ã¨ libero!": "Il passaggio Ã¨ libero!",
    "Il PokÃ©mon": "Il PokÃ©mon",
    "Il PokÃ©mon puÃ² ancora evolversi.": "Il PokÃ©mon puÃ² ancora evolversi.",
    "Il reroll Ã¨ disponibile solo a SKILL LV3.": "Il reroll Ã¨ disponibile solo a SKILL LV3.",
    "il suo amico": "il suo amico",
    "Il suo amico": "Il suo amico",
    "important": "important",
    "Impossibile completare la sostituzione.": "Impossibile completare la sostituzione.",
    "Incontro completato!": "Incontro completato!",
    "INCONTRO SUL PERCORSO": "INCONTRO SUL PERCORSO",
    "incubatorSteps": "incubatorSteps",
    "INEFFICACE": "INEFFICACE",
    "Inizia il soccorso: raggiungi il boss alla fine del passaggio.": "Inizia il soccorso: raggiungi il boss alla fine del passaggio.",
    "Inizia la campagna": "Inizia la campagna",
    "INIZIO": "INIZIO",
    "inventario": "inventario",
    "Inventario vuoto": "Inventario vuoto",
    "inventory-empty": "inventory-empty",
    "inventory-entry": "inventory-entry",
    "inventoryItems": "inventoryItems",
    "inventory-list": "inventory-list",
    "inventory-open": "inventory-open",
    "inventory-page-prev": "inventory-page-prev",
    "inventoryPager": "inventoryPager",
    "inventory-pager": "inventory-pager",
    "Iper Pozione": "Iper Pozione",
    "iper_pozione": "iper_pozione",
    "Iramella": "Iramella",
    "is-attacking": "is-attacking",
    "is-blurred": "is-blurred",
    "is-evolving": "is-evolving",
    "is-fainted is-revivable": "is-fainted is-revivable",
    "is-full": "is-full",
    "is-healable": "is-healable",
    "it": "it",
    "item-action-cancel": "item-action-cancel",
    "item-action-head": "item-action-head",
    "item-action-label": "item-action-label",
    "item-target-grid": "item-target-grid",
    "item-target-role": "item-target-role",
    "item-target-sprite": "item-target-sprite",
    "Ivysaur": "Ivysaur",
    "kakuna": "kakuna",
    "kanto": "kanto",
    "Kecleon": "Kecleon",
    "Kecleon pare scocciato": "Kecleon pare scocciato",
    "Kecleon ti osserva...": "Kecleon ti osserva...",
    "Kecleon ti osserva...  ...": "Kecleon ti osserva...  ...",
    "Kecleon ti osserva...  ... ...": "Kecleon ti osserva...  ... ...",
    "keydown": "keydown",
    "Krabby": "Krabby",
    "La sfida di Chansey": "La sfida di Chansey",
    "La squadra Ã¨ esausta": "La squadra Ã¨ esausta",
    "La squadra Ã¨ stata curata del 50% all\u0027arrivo.": "La squadra Ã¨ stata curata del 50% all\u0027arrivo.",
    "La squadra recupera il": "La squadra recupera il",
    "Lago Silente": "Lago Silente",
    "Latte Moomoo": "Latte Moomoo",
    "latte_moomoo": "latte_moomoo",
    "lava-cookie": "lava-cookie",
    "Lavottino": "Lavottino",
    "Le sinergie curano la squadra.": "Le sinergie curano la squadra.",
    "left": "left",
    "leftovers": "leftovers",
    "leggendaria": "leggendaria",
    "lemonade": "lemonade",
    "levelVal": "levelVal",
    "life-orb": "life-orb",
    "limonata": "limonata",
    "Limonata": "Limonata",
    "line": "line",
    "LIVELLI": "LIVELLI",
    "Livello 90 Â· entrerÃ nello slot S3.": "Livello 90 Â· entrerÃ nello slot S3.",
    "Lo Starter Ã¨ fisso: usa il Partner.": "Lo Starter Ã¨ fisso: usa il Partner.",
    "Lo Starter o il nemico non sono disponibili.": "Lo Starter o il nemico non sono disponibili.",
    "Lo zaino Ã¨ disponibile tra un nodo e il successivo.": "Lo zaino Ã¨ disponibile tra un nodo e il successivo.",
    "loading": "loading",
    "location.reload()": "location.reload()",
    "locked": "locked",
    "lotta": "lotta",
    "Luce Curativa": "Luce Curativa",
    "LV": "LV",
    "LV 1": "LV 1",
    "LV 90": "LV 90",
    "LV 90 Â· LV 90": "LV 90 Â· LV 90",
    "Maestro del Dojo": "Maestro del Dojo",
    "magnet": "magnet",
    "magnete": "magnete",
    "Magnete": "Magnete",
    "main-layout": "main-layout",
    "MANTIENI IL PARTNER ATTUALE": "MANTIENI IL PARTNER ATTUALE",
    "map": "map",
    "mapBackpackButton": "mapBackpackButton",
    "map-enemy-level": "map-enemy-level",
    "map-enemy-preview-crop": "map-enemy-preview-crop",
    "map-enemy-preview-final": "map-enemy-preview-final",
    "map-enemy-preview-final map-enemy-preview-second": "map-enemy-preview-final map-enemy-preview-second",
    "mapFloorButton": "mapFloorButton",
    "map-line": "map-line",
    "mapMenuButton": "mapMenuButton",
    "Mappa della run": "Mappa della run",
    "map-placeholder": "map-placeholder",
    "mapResetButton": "mapResetButton",
    "map-row": "map-row",
    "mapSvg": "mapSvg",
    "map-utility-actions": "map-utility-actions",
    "map-wrap": "map-wrap",
    "Marea Salva": "Marea Salva",
    "margin-top:8px": "margin-top:8px",
    "max": "max",
    "MAX": "MAX",
    "max_pozione": "max_pozione",
    "max_revive": "max_revive",
    "max-potion": "max-potion",
    "max-revive": "max-revive",
    "MEMBRO SQUADRA": "MEMBRO SQUADRA",
    "Mente Accelerata": "Mente Accelerata",
    "MENU": "MENU",
    "menu": "menu",
    "Menu": "Menu",
    "menu-box": "menu-box",
    "metal-coat": "metal-coat",
    "metalcoperta": "metalcoperta",
    "Metalcoperta": "Metalcoperta",
    "metapod": "metapod",
    "Mew": "Mew",
    "miracle-seed": "miracle-seed",
    "miracolseme": "miracolseme",
    "Miracolseme": "Miracolseme",
    "modal": "modal",
    "modal-box": "modal-box",
    "modal-child-open": "modal-child-open",
    "modalContent": "modalContent",
    "Moltres": "Moltres",
    "MONETE RACCOLTE": "MONETE RACCOLTE",
    "moo-moo-milk": "moo-moo-milk",
    "Morso Gelido": "Morso Gelido",
    "Mossa": "Mossa",
    "Mossa PokÃ©API non trovata": "Mossa PokÃ©API non trovata",
    "MOSSE": "MOSSE",
    "Mosse live PokeAPI: attive": "Mosse live PokeAPI: attive",
    "mousedown": "mousedown",
    "mouseup": "mouseup",
    "move": "move",
    "mystic-water": "mystic-water",
    "NEGOZIO": "NEGOZIO",
    "Nemici â†’ alleato casuale": "Nemici â†’ alleato casuale",
    "Nessun effetto": "Nessun effetto",
    "Nessun oggetto": "Nessun oggetto",
    "Nessun oggetto equipaggiato.": "Nessun oggetto equipaggiato.",
    "Nessun oggetto in questa tasca.": "Nessun oggetto in questa tasca.",
    "Nessun PokÃ©mon": "Nessun PokÃ©mon",
    "Nessun PokÃ©mon ha chiesto di unirsi alla squadra.": "Nessun PokÃ©mon ha chiesto di unirsi alla squadra.",
    "Nessun tipo alternativo disponibile per questa skill.": "Nessun tipo alternativo disponibile per questa skill.",
    "Nessun utilizzatore": "Nessun utilizzatore",
    "Nessuna carta raccolta": "Nessuna carta raccolta",
    "Nessuna carta scelta.": "Nessuna carta scelta.",
    "Nessuna descrizione disponibile.": "Nessuna descrizione disponibile.",
    "Nessuna descrizione.": "Nessuna descrizione.",
    "Nessuna mossa disponibile": "Nessuna mossa disponibile",
    "Nessuna riserva disponibile.": "Nessuna riserva disponibile.",
    "Nessuna skill disponibile per questo PokÃ©mon.": "Nessuna skill disponibile per questo PokÃ©mon.",
    "Nessuna skill LV3 disponibile.": "Nessuna skill LV3 disponibile.",
    "Nessuno Starter1 disponibile": "Nessuno Starter1 disponibile",
    "never-melt-ice": "never-melt-ice",
    "next()": "next()",
    "next(\u0027Dojo completato\u0027)": "next(\u0027Dojo completato\u0027)",
    "next(\u0027Negozio non disponibile\u0027)": "next(\u0027Negozio non disponibile\u0027)",
    "next(\u0027Negozio visitato\u0027)": "next(\u0027Negozio visitato\u0027)",
    "next(\u0027Negozio vuoto\u0027)": "next(\u0027Negozio vuoto\u0027)",
    "next(\u0027Premio del Dojo ottenuto\u0027)": "next(\u0027Premio del Dojo ottenuto\u0027)",
    "next(\u0027Vittoria!\u0027)": "next(\u0027Vittoria!\u0027)",
    "Nidorino": "Nidorino",
    "node": "node",
    "nodes": "nodes",
    "Nodi": "Nodi",
    "Nodi e scelte": "Nodi e scelte",
    "Nodo non disponibile": "Nodo non disponibile",
    "Non Ã¨ rimasto alcun oggetto.": "Non Ã¨ rimasto alcun oggetto.",
    "Non Ã¨ rimasto piÃ¹ nulla sugli scaffali.": "Non Ã¨ rimasto piÃ¹ nulla sugli scaffali.",
    "Non disponibile": "Non disponibile",
    "NON POTENZIARE": "NON POTENZIARE",
    "non_comune": "non_comune",
    "none": "none",
    "no-repeat": "no-repeat",
    "normal": "normal",
    "normale": "normale",
    "number": "number",
    "Number(p?.hp)": "Number(p?.hp)",
    "NUOVA AVVENTURA": "NUOVA AVVENTURA",
    "NUOVO POKÃ‰MON": "NUOVO POKÃ‰MON",
    "object": "object",
    "occhialineri": "occhialineri",
    "Occhialineri": "Occhialineri",
    "Oddish": "Oddish",
    "OGGETTI": "OGGETTI",
    "oggetti": "oggetti",
    "Oggetti rapidi": "Oggetti rapidi",
    "OGGETTO": "OGGETTO",
    "Oggetto": "Oggetto",
    "Oggetto casuale ottenuto": "Oggetto casuale ottenuto",
    "Oggetto curativo": "Oggetto curativo",
    "OGGETTO EQUIPAGGIABILE": "OGGETTO EQUIPAGGIABILE",
    "oggetto equipaggiato corrisponde al tipo dell": "oggetto equipaggiato corrisponde al tipo dell",
    "Oggetto non disponibile.": "Oggetto non disponibile.",
    "Oggetto non equipaggiato.": "Oggetto non equipaggiato.",
    "Oggetto o PokÃ©mon non disponibile.": "Oggetto o PokÃ©mon non disponibile.",
    "OGGETTO OTTENUTO": "OGGETTO OTTENUTO",
    "Oggetto PokÃ©API non trovato": "Oggetto PokÃ©API non trovato",
    "Oggetto tenuto": "Oggetto tenuto",
    "OGGETTO USABILE": "OGGETTO USABILE",
    "Ogni PokÃ©mon vivo agisce una volta. La VelocitÃ  decide chi parte prima.": "Ogni PokÃ©mon vivo agisce una volta. La VelocitÃ  decide chi parte prima.",
    "old-gateau": "old-gateau",
    "onclick": "onclick",
    "onclick=": "onclick=",
    "ondragover=": "ondragover=",
    "ondragstart=": "ondragstart=",
    "ondrop=": "ondrop=",
    "onpointercancel=": "onpointercancel=",
    "onpointerleave=": "onpointerleave=",
    "onpointerup=": "onpointerup=",
    "opacity:.5;font-size:11px": "opacity:.5;font-size:11px",
    "openGuideCategory(\u0027combat\u0027)": "openGuideCategory(\u0027combat\u0027)",
    "openGuideCategory(\u0027map\u0027)": "openGuideCategory(\u0027map\u0027)",
    "openGuideCategory(\u0027team\u0027)": "openGuideCategory(\u0027team\u0027)",
    "openGuideMenu()": "openGuideMenu()",
    "openHomeMenu()": "openHomeMenu()",
    "openSecondPreview()": "openSecondPreview()",
    "openStarterPreview()": "openStarterPreview()",
    "p?.immagine \u0026\u0026 Number(p.stage)": "p?.immagine \u0026\u0026 Number(p.stage)",
    "Pagina precedente": "Pagina precedente",
    "Palla Fumo (Smoke Ball)": "Palla Fumo (Smoke Ball)",
    "palla_fumo": "palla_fumo",
    "Palude Azzurra": "Palude Azzurra",
    "Paras": "Paras",
    "Partner": "Partner",
    "PARTNER": "PARTNER",
    "Partner non equipaggiato.": "Partner non equipaggiato.",
    "PASSAGGIO": "PASSAGGIO",
    "Passo di Vento": "Passo di Vento",
    "per lasciarti passare.": "per lasciarti passare.",
    "Percorso": "Percorso",
    "Permette sempre di fuggire dagli incontri selvatici.": "Permette sempre di fuggire dagli incontri selvatici.",
    "perPage ? `": "perPage ? `",
    "physical": "physical",
    "Piano corrente": "Piano corrente",
    "PIANO RAGGIUNTO": "PIANO RAGGIUNTO",
    "PIANO: 1": "PIANO: 1",
    "piAtk": "piAtk",
    "piAtkR": "piAtkR",
    "piCrit": "piCrit",
    "piDef": "piDef",
    "piDefR": "piDefR",
    "Pidgeot": "Pidgeot",
    "Pidgeotto": "Pidgeotto",
    "Pidgey": "Pidgey",
    "pietradura": "pietradura",
    "Pietradura": "Pietradura",
    "piEva": "piEva",
    "piHp": "piHp",
    "piSpd": "piSpd",
    "piSpdR": "piSpdR",
    "piStun": "piStun",
    "PKM_DB:": "PKM_DB:",
    "player-0": "player-0",
    "player-1": "player-1",
    "player-2": "player-2",
    "player-3": "player-3",
    "player-4": "player-4",
    "POCO EFFICACE": "POCO EFFICACE",
    "pointerdown": "pointerdown",
    "poison-barb": "poison-barb",
    "PokÃ©mon": "PokÃ©mon",
    "PokÃ©mon caricati": "PokÃ©mon caricati",
    "PokÃ©mon non disponibile.": "PokÃ©mon non disponibile.",
    "PokÃ©mon selvatici": "PokÃ©mon selvatici",
    "POKÃ‰MON DA RECLUTARE": "POKÃ‰MON DA RECLUTARE",
    "pokeapi:ready": "pokeapi:ready",
    "pokeInfo": "pokeInfo",
    "pokeInfoActions": "pokeInfoActions",
    "pokeInfoName": "pokeInfoName",
    "pokeInfoSprite": "pokeInfoSprite",
    "pokeInfoTypes": "pokeInfoTypes",
    "PokeMisteryRL": "PokeMisteryRL",
    "PokeMisteryRL.Helpers.closeModal()": "PokeMisteryRL.Helpers.closeModal()",
    "pokeMisteryRL.pokeapi.item-icons.v1": "pokeMisteryRL.pokeapi.item-icons.v1",
    "pokeMisteryRL.pokeapi.kanto.v1": "pokeMisteryRL.pokeapi.kanto.v1",
    "PokeMisteryRL.Run.startPokemon() non disponibile.": "PokeMisteryRL.Run.startPokemon() non disponibile.",
    "PokeMisteryRL.UI.allowBackpackDrop(event)": "PokeMisteryRL.UI.allowBackpackDrop(event)",
    "PokeMisteryRL.UI.allowTestBottomDrop(event)": "PokeMisteryRL.UI.allowTestBottomDrop(event)",
    "PokeMisteryRL.UI.changeInventoryPage(-1)": "PokeMisteryRL.UI.changeInventoryPage(-1)",
    "PokeMisteryRL.UI.closeTest2Backpack()": "PokeMisteryRL.UI.closeTest2Backpack()",
    "PokeMisteryRL.UI.openTestBackpack()": "PokeMisteryRL.UI.openTestBackpack()",
    "pokemon ? `": "pokemon ? `",
    "pokemon?.immagine \u0026\u0026 Number(pokemon.stage || 1)": "pokemon?.immagine \u0026\u0026 Number(pokemon.stage || 1)",
    "pokemon-status-particles": "pokemon-status-particles",
    "pokePreview": "pokePreview",
    "Poliwag": "Poliwag",
    "PORTAFOGLIO": "PORTAFOGLIO",
    "position": "position",
    "Posizioni squadra": "Posizioni squadra",
    "potenziamento": "potenziamento",
    "potenziamento_tipo": "potenziamento_tipo",
    "potion": "potion",
    "power": "power",
    "pozione": "pozione",
    "Pozione": "Pozione",
    "Pozione Max": "Pozione Max",
    "pp-actions": "pp-actions",
    "pp-close": "pp-close",
    "ppCustomContent": "ppCustomContent",
    "ppDef": "ppDef",
    "pp-health": "pp-health",
    "pp-health-label": "pp-health-label",
    "ppHpFill": "ppHpFill",
    "ppHpText": "ppHpText",
    "pp-identity": "pp-identity",
    "ppk": "ppk",
    "ppLevel": "ppLevel",
    "ppName": "ppName",
    "pp-profile-head": "pp-profile-head",
    "ppSkill": "ppSkill",
    "pp-skill-boosted-power": "pp-skill-boosted-power",
    "ppSkillName": "ppSkillName",
    "pp-skill-name": "pp-skill-name",
    "pp-skill-pill": "pp-skill-pill",
    "ppSkillPower": "ppSkillPower",
    "pp-skill-power": "pp-skill-power",
    "pp-skills": "pp-skills",
    "pp-skill-type": "pp-skill-type",
    "ppSpd": "ppSpd",
    "ppSprite": "ppSprite",
    "pp-sprite-frame": "pp-sprite-frame",
    "pp-stat-boosted": "pp-stat-boosted",
    "pp-stats": "pp-stats",
    "ppTypes": "ppTypes",
    "PREMIO": "PREMIO",
    "Premio del Rifugio ottenuto": "Premio del Rifugio ottenuto",
    "Prenditi cura della squadra prima di proseguire.": "Prenditi cura della squadra prima di proseguire.",
    "preview-box": "preview-box",
    "preview-held-item": "preview-held-item",
    "PREZZO": "PREZZO",
    "PrioritÃ  dei bersagli": "PrioritÃ  dei bersagli",
    "PROMISE REJECTION": "PROMISE REJECTION",
    "PROSEGUI": "PROSEGUI",
    "Prova di combattimento": "Prova di combattimento",
    "PS": "PS",
    "psico": "psico",
    "Psyduck": "Psyduck",
    "Punto di ristoro": "Punto di ristoro",
    "Puoi avere al massimo 5 oggetti attivi.": "Puoi avere al massimo 5 oggetti attivi.",
    "Puoi cambiare il compagno prima dello scontro.": "Puoi cambiare il compagno prima dello scontro.",
    "PWR mosse +30% Â· rinculo 10% HP": "PWR mosse +30% Â· rinculo 10% HP",
    "Questo oggetto Ã¨ un consumabile: usalo dallo zaino.": "Questo oggetto Ã¨ un consumabile: usalo dallo zaino.",
    "Questo oggetto va usato, non equipaggiato.": "Questo oggetto va usato, non equipaggiato.",
    "Questo PokÃ©mon Ã¨ esausto: usa RIANIMA.": "Questo PokÃ©mon Ã¨ esausto: usa RIANIMA.",
    "Questo PokÃ©mon non Ã¨ esausto.": "Questo PokÃ©mon non Ã¨ esausto.",
    "quick-item-detail-description": "quick-item-detail-description",
    "quick-item-detail-icon": "quick-item-detail-icon",
    "quick-item-icon": "quick-item-icon",
    "quickItemSlots": "quickItemSlots",
    "quickReset()": "quickReset()",
    "RACCOGLITORE CARTE": "RACCOGLITORE CARTE",
    "Raddoppia il denaro vinto se il possessore partecipa alla lotta.": "Raddoppia il denaro vinto se il possessore partecipa alla lotta.",
    "Radici Profonde": "Radici Profonde",
    "Radure Tossiche": "Radure Tossiche",
    "rage-candy-bar": "rage-candy-bar",
    "Rallenta": "Rallenta",
    "Rallenta del 40%": "Rallenta del 40%",
    "rallentamento": "rallentamento",
    "rara": "rara",
    "rare-candy": "rare-candy",
    "reazione": "reazione",
    "recruit-card": "recruit-card",
    "recruit-card-info": "recruit-card-info",
    "recruit-card-main": "recruit-card-main",
    "recruit-card-sprite": "recruit-card-sprite",
    "recruit-card-title": "recruit-card-title",
    "recruit-close-x": "recruit-close-x",
    "recruit-compare-actions": "recruit-compare-actions",
    "recruit-compare-arrow": "recruit-compare-arrow",
    "recruit-compare-grid": "recruit-compare-grid",
    "recruit-compare-note": "recruit-compare-note",
    "recruit-divider": "recruit-divider",
    "recruit-empty": "recruit-empty",
    "Recruitment system non disponibile": "Recruitment system non disponibile",
    "recruitment-box recruit-compare": "recruitment-box recruit-compare",
    "recruitment-box recruit-full-team": "recruitment-box recruit-full-team",
    "recruitment-kicker": "recruitment-kicker",
    "recruitment-offer-actions": "recruitment-offer-actions",
    "recruitment-offer-main": "recruitment-offer-main",
    "recruitment-offer-reward": "recruitment-offer-reward",
    "recruit-name": "recruit-name",
    "recruit-option": "recruit-option",
    "recruit-options": "recruit-options",
    "recruit-skill": "recruit-skill",
    "recruit-stats": "recruit-stats",
    "red": "red",
    "region-choice campaign-choice": "region-choice campaign-choice",
    "rejectShelterChallenge()": "rejectShelterChallenge()",
    "rejectSkillChallenge()": "rejectSkillChallenge()",
    "releaseSecond()": "releaseSecond()",
    "REROLL": "REROLL",
    "Reroll giÃ  usato in questo nodo Skill.": "Reroll giÃ  usato in questo nodo Skill.",
    "REROLL TIPO SKILL Â· 100 Â¥": "REROLL TIPO SKILL Â· 100 Â¥",
    "Reset run": "Reset run",
    "Revitalizzante Max": "Revitalizzante Max",
    "revival-herb": "revival-herb",
    "revive": "revive",
    "RIANIMA Â· 100 ðŸ’°": "RIANIMA Â· 100 ðŸ’°",
    "Rianima con il 50% degli HP.": "Rianima con il 50% degli HP.",
    "Rianima con tutti gli HP e cura gli status.": "Rianima con tutti gli HP e cura gli status.",
    "Rianima con tutti gli HP.": "Rianima con tutti gli HP.",
    "Ricomincia": "Ricomincia",
    "Ricomincia la run": "Ricomincia la run",
    "RICOMPENSA": "RICOMPENSA",
    "Ricompensa non disponibile.": "Ricompensa non disponibile.",
    "Ricompensa vittoria:": "Ricompensa vittoria:",
    "Ricompensa:": "Ricompensa:",
    "RIFIUTA": "RIFIUTA",
    "Riflette 10%": "Riflette 10%",
    "Riflette 25% e maledice": "Riflette 25% e maledice",
    "Rifugio": "Rifugio",
    "rifugio": "rifugio",
    "rightMainPanel": "rightMainPanel",
    "Ripristino Totale": "Ripristino Totale",
    "ripristino_totale": "ripristino_totale",
    "RIPROVA": "RIPROVA",
    "Ritmo da Combattimento": "Ritmo da Combattimento",
    "Ritorsione Oscura": "Ritorsione Oscura",
    "Rive Ventose": "Rive Ventose",
    "rivitalizzante": "rivitalizzante",
    "Rivitalizzante": "Rivitalizzante",
    "roccia": "roccia",
    "rocky-helmet": "rocky-helmet",
    "RUBA": "RUBA",
    "runLogArrow": "runLogArrow",
    "runLogContent": "runLogContent",
    "run-log-line": "run-log-line",
    "run-victory-team": "run-victory-team",
    "Ruscello Muschioso": "Ruscello Muschioso",
    "S1": "S1",
    "s1": "s1",
    "S1 â†’ terzo libero": "S1 â†’ terzo libero",
    "s1HeldItem": "s1HeldItem",
    "s2": "s2",
    "S2": "S2",
    "S2 â†’ secondo libero": "S2 â†’ secondo libero",
    "s2AtkVal": "s2AtkVal",
    "s2-choice-info": "s2-choice-info",
    "s2-choice-list": "s2-choice-list",
    "s2-choice-types": "s2-choice-types",
    "s2-current": "s2-current",
    "s2DefVal": "s2DefVal",
    "s2HeldItem": "s2HeldItem",
    "s2HpBar": "s2HpBar",
    "s2HpTxt": "s2HpTxt",
    "s2HudSection": "s2HudSection",
    "s2Level": "s2Level",
    "s2Name": "s2Name",
    "s2SpdVal": "s2SpdVal",
    "s2-tab-close": "s2-tab-close",
    "s2Typing": "s2Typing",
    "s3": "s3",
    "S3": "S3",
    "S3 â†’ primo libero": "S3 â†’ primo libero",
    "S3 cerca il primo nemico libero, S2 il secondo, S1 il terzo. I nemici scelgono casualmente un alleato vivo.": "S3 cerca il primo nemico libero, S2 il secondo, S1 il terzo. I nemici scelgono casualmente un alleato vivo.",
    "sacred-ash": "sacred-ash",
    "safari": "safari",
    "SALTA": "SALTA",
    "Santuario delle Quattro Correnti": "Santuario delle Quattro Correnti",
    "satk": "satk",
    "SCAFFALI": "SCAFFALI",
    "SCEGLI CHI LO DEVE TENERE": "SCEGLI CHI LO DEVE TENERE",
    "Scegli chi potenziare": "Scegli chi potenziare",
    "Scegli il Partner": "Scegli il Partner",
    "Scegli il tipo": "Scegli il tipo",
    "Scegli quale PokÃ©mon potenziare.": "Scegli quale PokÃ©mon potenziare.",
    "SCEGLI SU CHI USARLO": "SCEGLI SU CHI USARLO",
    "Scegli un argomento": "Scegli un argomento",
    "Scegli un membro per cambiare il tipo della sua skill attiva.": "Scegli un membro per cambiare il tipo della sua skill attiva.",
    "Scegli un membro su cui usarlo": "Scegli un membro su cui usarlo",
    "Scegli un oggetto": "Scegli un oggetto",
    "Scegli una carta": "Scegli una carta",
    "Scegli una coppia: entrambi entrano in squadra al livello 90.": "Scegli una coppia: entrambi entrano in squadra al livello 90.",
    "Schema prioritÃ  bersagli": "Schema prioritÃ  bersagli",
    "Sciame di Riserva": "Sciame di Riserva",
    "Sciarpaseta": "Sciarpaseta",
    "sciarpaseta": "sciarpaseta",
    "Scossa Paralizzante": "Scossa Paralizzante",
    "scudo": "scudo",
    "sdef": "sdef",
    "Se puÃ² evolversi: Difesa Ã—1,5.": "Se puÃ² evolversi: Difesa Ã—1,5.",
    "Seel": "Seel",
    "Segui solo i collegamenti illuminati: ogni nodo apre il tratto successivo.": "Segui solo i collegamenti illuminati: ogni nodo apre il tratto successivo.",
    "SELECTED POKÃ‰MON LV +1.": "SELECTED POKÃ‰MON LV +1.",
    "Seleziona un oggetto": "Seleziona un oggetto",
    "Selva Antica": "Selva Antica",
    "Sentiero Verde": "Sentiero Verde",
    "Serve uno Starter per combattere.": "Serve uno Starter per combattere.",
    "Servono 100 monete.": "Servono 100 monete.",
    "Sfida accettata": "Sfida accettata",
    "Sfida affrontata": "Sfida affrontata",
    "SFIDA DEL RIFUGIO Â· LV 1": "SFIDA DEL RIFUGIO Â· LV 1",
    "SFIDA IN CORSO": "SFIDA IN CORSO",
    "Sfida in corso": "Sfida in corso",
    "Sfida non affrontata": "Sfida non affrontata",
    "sharp-beak": "sharp-beak",
    "Shellder": "Shellder",
    "shelter": "shelter",
    "shelter-challenge-actions": "shelter-challenge-actions",
    "shelter-challenge-card": "shelter-challenge-card",
    "shelter-challenge-header": "shelter-challenge-header",
    "shelter-challenge-identity": "shelter-challenge-identity",
    "shelter-challenge-moves": "shelter-challenge-moves",
    "shelter-challenge-reward": "shelter-challenge-reward",
    "shelter-challenge-stats": "shelter-challenge-stats",
    "shelter-hp-text": "shelter-hp-text",
    "shelter-hp-track": "shelter-hp-track",
    "shelter-member shelter-member-empty": "shelter-member shelter-member-empty",
    "shelter-member-info": "shelter-member-info",
    "shelter-member-label": "shelter-member-label",
    "shelter-member-sprite": "shelter-member-sprite",
    "shelter-member-status": "shelter-member-status",
    "shelter-revive-cost": "shelter-revive-cost",
    "shelter-roster": "shelter-roster",
    "shielded": "shielded",
    "shop": "shop",
    "Shop": "Shop",
    "shop-actions": "shop-actions",
    "shop-card": "shop-card",
    "shop-eyebrow": "shop-eyebrow",
    "shop-header": "shop-header",
    "shop-header-copy": "shop-header-copy",
    "shop-icon": "shop-icon",
    "shop-item-cost": "shop-item-cost",
    "shop-item-kicker": "shop-item-kicker",
    "shop-item-modal-icon": "shop-item-modal-icon",
    "shopkeeper-frame": "shopkeeper-frame",
    "shop-leave": "shop-leave",
    "shop-list": "shop-list",
    "shop-name": "shop-name",
    "shop-no-offers": "shop-no-offers",
    "shop-shelves": "shop-shelves",
    "shop-shelves-title": "shop-shelves-title",
    "shop-stage": "shop-stage",
    "shop-wallet": "shop-wallet",
    "Si diffonde al KO": "Si diffonde al KO",
    "sideName": "sideName",
    "sideSprite": "sideSprite",
    "sideTyping": "sideTyping",
    "silk-scarf": "silk-scarf",
    "silver-powder": "silver-powder",
    "sinergia": "sinergia",
    "skill": "skill",
    "SKILL": "SKILL",
    "SKILL AL MASSIMO": "SKILL AL MASSIMO",
    "SKILL LV3": "SKILL LV3",
    "SKILL MAX": "SKILL MAX",
    "Skill System non disponibile.": "Skill System non disponibile.",
    "skill-arrow": "skill-arrow",
    "skill-choice-body": "skill-choice-body",
    "skill-choice-card": "skill-choice-card",
    "skill-choice-card skill-choice-empty": "skill-choice-card skill-choice-empty",
    "skill-choice-head": "skill-choice-head",
    "skill-choice-list": "skill-choice-list",
    "skill-choice-moves": "skill-choice-moves",
    "skill-choice-sprite": "skill-choice-sprite",
    "skill-move-box": "skill-move-box",
    "skill-move-box skill-move-next": "skill-move-box skill-move-next",
    "skill-move-box skill-result-new": "skill-move-box skill-result-new",
    "skill-move-box skill-result-old": "skill-move-box skill-result-old",
    "skill-node-subtitle": "skill-node-subtitle",
    "skill-result-flow": "skill-result-flow",
    "SLOT": "SLOT",
    "slot alto": "slot alto",
    "slot basso": "slot basso",
    "slot davanti": "slot davanti",
    "Slot e vita": "Slot e vita",
    "Slot oggetto vuoto": "Slot oggetto vuoto",
    "SLOT VUOTO": "SLOT VUOTO",
    "small": "small",
    "smoke-ball": "smoke-ball",
    "Soda Pop": "Soda Pop",
    "soda_pop": "soda_pop",
    "soda-pop": "soda-pop",
    "Soffice Sabbia": "Soffice Sabbia",
    "soffice_sabbia": "soffice_sabbia",
    "Soffio Travolgente": "Soffio Travolgente",
    "soft-sand": "soft-sand",
    "SOLDI": "SOLDI",
    "Soldi": "Soldi",
    "SOSTITUISCI": "SOSTITUISCI",
    "SPA": "SPA",
    "span": "span",
    "spd": "spd",
    "SPD": "SPD",
    "spdVal": "spdVal",
    "special": "special",
    "special-attack": "special-attack",
    "special-defense": "special-defense",
    "speciale": "speciale",
    "spell-tag": "spell-tag",
    "spettro": "spettro",
    "Spettrotarga": "Spettrotarga",
    "spettrotarga": "spettrotarga",
    "SQUADRA": "SQUADRA",
    "Squadra": "Squadra",
    "Squadra al rifugio": "Squadra al rifugio",
    "Squadra contro avversari": "Squadra contro avversari",
    "Squadra piena": "Squadra piena",
    "Squirtle": "Squirtle",
    "src=": "src=",
    "sr-only": "sr-only",
    "Starmie": "Starmie",
    "STARTER": "STARTER",
    "Starter": "Starter",
    "STARTER 1": "STARTER 1",
    "STARTER 2": "STARTER 2",
    "Starter non disponibile.": "Starter non disponibile.",
    "Starter principale": "Starter principale",
    "starter1Box": "starter1Box",
    "starter2Placeholder": "starter2Placeholder",
    "starter2Slot": "starter2Slot",
    "starter2Sprite": "starter2Sprite",
    "startPokemon:": "startPokemon:",
    "startWaveBossChallenge()": "startWaveBossChallenge()",
    "Staryu": "Staryu",
    "statistica": "statistica",
    "STATISTICHE": "STATISTICHE",
    "Statistiche del piano corrente": "Statistiche del piano corrente",
    "status-poisoned": "status-poisoned",
    "status-stunned": "status-stunned",
    "stordimento": "stordimento",
    "Stordisce": "Stordisce",
    "string": "string",
    "style": "style",
    "style=": "style=",
    "stylesheet": "stylesheet",
    "Super Pozione": "Super Pozione",
    "super_pozione": "super_pozione",
    "SUPEREFFICACE": "SUPEREFFICACE",
    "super-potion": "super-potion",
    "Tangela": "Tangela",
    "tank": "tank",
    "targeting": "targeting",
    "team": "team",
    "team-": "team-",
    "teamCount": "teamCount",
    "team-nav": "team-nav",
    "teamNextBtn": "teamNextBtn",
    "teamPrevBtn": "teamPrevBtn",
    "teamViewer": "teamViewer",
    "teamViewerLevel": "teamViewerLevel",
    "teamViewerName": "teamViewerName",
    "teamViewerSprite": "teamViewerSprite",
    "Tentacool": "Tentacool",
    "Tentacruel": "Tentacruel",
    "terra": "terra",
    "Terzo colpo +30%": "Terzo colpo +30%",
    "Terzo colpo +70%": "Terzo colpo +70%",
    "Test2": "Test2",
    "test2": "test2",
    "test2-backpack-back": "test2-backpack-back",
    "test2-backpack-close": "test2-backpack-close",
    "test2-backpack-map": "test2-backpack-map",
    "test2-backpack-map test2-backpack-info-map": "test2-backpack-map test2-backpack-info-map",
    "test2-backpack-panel": "test2-backpack-panel",
    "test2-backpack-tabs": "test2-backpack-tabs",
    "test2BitsReadout": "test2BitsReadout",
    "test2-boss1-group": "test2-boss1-group",
    "test2-boss-intro": "test2-boss-intro",
    "test2-boss-intro-details": "test2-boss-intro-details",
    "test2-boss-intro-map": "test2-boss-intro-map",
    "test2CampaignButton": "test2CampaignButton",
    "test2-challenger-level": "test2-challenger-level",
    "test2-companion-choice-map": "test2-companion-choice-map",
    "test2-companion-choice-panel": "test2-companion-choice-panel",
    "test2-dojo-actions": "test2-dojo-actions",
    "test2-dojo-challenge-body": "test2-dojo-challenge-body",
    "test2-dojo-challenger": "test2-dojo-challenger",
    "test2-dojo-hud test2-dojo-challenge-hud": "test2-dojo-hud test2-dojo-challenge-hud",
    "test2-dojo-item-targets": "test2-dojo-item-targets",
    "test2-dojo-map": "test2-dojo-map",
    "test2-dojo-map test2-dojo-fight-pending": "test2-dojo-map test2-dojo-fight-pending",
    "test2-dojo-prize-panel test2-dojo-item-choice": "test2-dojo-prize-panel test2-dojo-item-choice",
    "test2-dojo-prize-panel test2-dojo-item-win": "test2-dojo-prize-panel test2-dojo-item-win",
    "test2-dojo-prize-panel test2-dojo-skill-choice": "test2-dojo-prize-panel test2-dojo-skill-choice",
    "test2-dojo-prize-panel test2-dojo-type-choice": "test2-dojo-prize-panel test2-dojo-type-choice",
    "test2-dojo-skill-list": "test2-dojo-skill-list",
    "test2-dojo-skill-target": "test2-dojo-skill-target",
    "test2-dojo-type-options": "test2-dojo-type-options",
    "test2-dojo-versus": "test2-dojo-versus",
    "test2-dojo-victory-shake": "test2-dojo-victory-shake",
    "test2-event-item-scene": "test2-event-item-scene",
    "test2-event-reward-map": "test2-event-reward-map",
    "test2-event-reward-panel": "test2-event-reward-panel",
    "test2-evolution-flash test2-scene-evolution": "test2-evolution-flash test2-scene-evolution",
    "test2-fight-bottom": "test2-fight-bottom",
    "test2-fight-versus": "test2-fight-versus",
    "test2FloorReadout": "test2FloorReadout",
    "test2FormationLine": "test2FormationLine",
    "test2-formation-order": "test2-formation-order",
    "test2-horizontal-map": "test2-horizontal-map",
    "test2-item-effect-card": "test2-item-effect-card",
    "test2-item-info-icon": "test2-item-info-icon",
    "test2-item-info-main": "test2-item-info-main",
    "test2-item-info-panel": "test2-item-info-panel",
    "test2-item-targets": "test2-item-targets",
    "test2-kecleon-bubble": "test2-kecleon-bubble",
    "test2-layout": "test2-layout",
    "--test2-map-shift": "--test2-map-shift",
    "test2-member-item": "test2-member-item",
    "test2-member-portrait": "test2-member-portrait",
    "test2-node-finish": "test2-node-finish",
    "test2-recruit-accept": "test2-recruit-accept",
    "test2-recruit-candidate": "test2-recruit-candidate",
    "test2-recruit-choice": "test2-recruit-choice",
    "test2-recruit-choice-card": "test2-recruit-choice-card",
    "test2-recruit-dialogue-mark": "test2-recruit-dialogue-mark",
    "test2-recruit-eyebrow": "test2-recruit-eyebrow",
    "test2-recruit-reject": "test2-recruit-reject",
    "test2-recruit-replace-card": "test2-recruit-replace-card",
    "test2-recruit-scene": "test2-recruit-scene",
    "test2-rescue-friend": "test2-rescue-friend",
    "test2-rescue-mon rescue-mon-1": "test2-rescue-mon rescue-mon-1",
    "test2-rescue-prompt-map": "test2-rescue-prompt-map",
    "test2-rescue-prompt-panel": "test2-rescue-prompt-panel",
    "test2-rescue-requester": "test2-rescue-requester",
    "test2-rescue-request-scene": "test2-rescue-request-scene",
    "test2-rescue-reward-map": "test2-rescue-reward-map",
    "test2-rescue-reward-panel": "test2-rescue-reward-panel",
    "test2-rescue-reward-scene": "test2-rescue-reward-scene",
    "test2-rescue-summary": "test2-rescue-summary",
    "test2-reset": "test2-reset",
    "test2-shelter-chansey": "test2-shelter-chansey",
    "test2-shelter-items": "test2-shelter-items",
    "test2-shelter-map": "test2-shelter-map",
    "test2-shelter-map test2-shelter-fight-pending": "test2-shelter-map test2-shelter-fight-pending",
    "test2-shelter-members": "test2-shelter-members",
    "test2-shelter-offer": "test2-shelter-offer",
    "test2-shelter-panel": "test2-shelter-panel",
    "test2-shelter-reroll": "test2-shelter-reroll",
    "test2-shop-close": "test2-shop-close",
    "test2-shop-detail": "test2-shop-detail",
    "test2-shop-detail-actions": "test2-shop-detail-actions",
    "test2-shop-detail-icon": "test2-shop-detail-icon",
    "test2-shop-grid": "test2-shop-grid",
    "test2-shop-item": "test2-shop-item",
    "test2-shop-kecleon": "test2-shop-kecleon",
    "test2-shop-map": "test2-shop-map",
    "test2-shop-panel": "test2-shop-panel",
    "test2-starter-choice-map": "test2-starter-choice-map",
    "test2-starter-choice-panel": "test2-starter-choice-panel",
    "test2-toll-group": "test2-toll-group",
    "test2-toll-map": "test2-toll-map",
    "test2-toll-panel": "test2-toll-panel",
    "test2-utility-bar": "test2-utility-bar",
    "test2-utility-floor": "test2-utility-floor",
    "test2-utility-money": "test2-utility-money",
    "test-backpack-content": "test-backpack-content",
    "test-backpack-items": "test-backpack-items",
    "test-backpack-pockets": "test-backpack-pockets",
    "test-backpack-target": "test-backpack-target",
    "test-backpack-team": "test-backpack-team",
    "text-align:center": "text-align:center",
    "Ti sto osservandoâ€¦": "Ti sto osservandoâ€¦",
    "TIENI PREMUTO UN OGGETTO PER LA DESCRIZIONE": "TIENI PREMUTO UN OGGETTO PER LA DESCRIZIONE",
    "Tipi di nodo": "Tipi di nodo",
    "TIPO LOTTA": "TIPO LOTTA",
    "title=": "title=",
    "toggleInventory()": "toggleInventory()",
    "toll": "toll",
    "top": "top",
    "Torna al menu": "Torna al menu",
    "TORNA ALLA HOME": "TORNA ALLA HOME",
    "torre": "torre",
    "torta_antica": "torta_antica",
    "Tossina Persistente": "Tossina Persistente",
    "touchend": "touchend",
    "touchstart": "touchstart",
    "transform": "transform",
    "translate(-50%, -50%)": "translate(-50%, -50%)",
    "Trascina i tre slot per cambiare l\u0027ordine prima del prossimo nodo.": "Trascina i tre slot per cambiare l\u0027ordine prima del prossimo nodo.",
    "Trascina sul PokÃ©mon o scegli il membro": "Trascina sul PokÃ©mon o scegli il membro",
    "Trascina un PokÃ©mon nello slot desiderato.": "Trascina un PokÃ©mon nello slot desiderato.",
    "true": "true",
    "tunnel": "tunnel",
    "Turni": "Turni",
    "turns": "turns",
    "Tutta la squadra sale di livello.": "Tutta la squadra sale di livello.",
    "twisted-spoon": "twisted-spoon",
    "type-": "type-",
    "type-card-bonus-copy": "type-card-bonus-copy",
    "type-card-bonus-list": "type-card-bonus-list",
    "type-card-bonus-row": "type-card-bonus-row",
    "type-card-collector-entry": "type-card-collector-entry",
    "type-card-users": "type-card-users",
    "Ultimo avvertimento!": "Ultimo avvertimento!",
    "Un gruppo di PokÃ©mon blocca la strada.": "Un gruppo di PokÃ©mon blocca la strada.",
    "Un maestro del Dojo mette alla prova la tua squadra.": "Un maestro del Dojo mette alla prova la tua squadra.",
    "Una Skill crescerÃ di livello.": "Una Skill crescerÃ di livello.",
    "undefined": "undefined",
    "unequipSecond()": "unequipSecond()",
    "unhandledrejection": "unhandledrejection",
    "Uovo": "Uovo",
    "uovo": "uovo",
    "USA": "USA",
    "USA IL RIFUGIO": "USA IL RIFUGIO",
    "USA OGGETTO": "USA OGGETTO",
    "USA ORA": "USA ORA",
    "USA SU": "USA SU",
    "USABILE": "USABILE",
    "USABILI": "USABILI",
    "USABILI Â· TOCCA E SCEGLI IL MEMBRO": "USABILI Â· TOCCA E SCEGLI IL MEMBRO",
    "usable": "usable",
    "Usalo su un PokÃ©mon esausto.": "Usalo su un PokÃ©mon esausto.",
    "use strict": "use strict",
    "useInventoryItem": "useInventoryItem",
    "utf-8": "utf-8",
    "VAI AL RIFUGIO": "VAI AL RIFUGIO",
    "VEL": "VEL",
    "Velenaculeo": "Velenaculeo",
    "velenaculeo": "velenaculeo",
    "veleno": "veleno",
    "velenoculeo": "velenoculeo",
    "VELOCITÃ€": "VELOCITÃ€",
    "Venomoth": "Venomoth",
    "Venonat": "Venonat",
    "Venusaur": "Venusaur",
    "Victreebel": "Victreebel",
    "viewport": "viewport",
    "Vileplume": "Vileplume",
    "Vinci e ricevi 2 oggetti curativi.": "Vinci e ricevi 2 oggetti curativi.",
    "Vita": "Vita",
    "VITA PIENA": "VITA PIENA",
    "Vittoria al Dojo!": "Vittoria al Dojo!",
    "Vittoria!": "Vittoria!",
    "VITTORIA!": "VITTORIA!",
    "volante": "volante",
    "Voltorb": "Voltorb",
    "vorrebbe partecipare alla tua squadra": "vorrebbe partecipare alla tua squadra",
    "VS": "VS",
    "vulneropolizza": "vulneropolizza",
    "Vulneropolizza (Weakness Policy)": "Vulneropolizza (Weakness Policy)",
    "Vuoi accoglierlo nel gruppo?": "Vuoi accoglierlo nel gruppo?",
    "Vuole continuare lâ€™avventura al fianco della tua squadra.": "Vuole continuare lâ€™avventura al fianco della tua squadra.",
    "Vuole testare la tua squadra prima di aiutarti.": "Vuole testare la tua squadra prima di aiutarti.",
    "Vuoto": "Vuoto",
    "Wartortle": "Wartortle",
    "weakness-policy": "weakness-policy",
    "weedle": "weedle",
    "Weepinbell": "Weepinbell",
    "width:0%": "width:0%",
    "width:100%": "width:100%",
    "width=device-width,initial-scale=1": "width=device-width,initial-scale=1",
    "window.acceptRecruitment()": "window.acceptRecruitment()",
    "window.backRecruitmentSelection()": "window.backRecruitmentSelection()",
    "window.cancelFullTeamRecruitment()": "window.cancelFullTeamRecruitment()",
    "window.confirmRecruitReplacement()": "window.confirmRecruitReplacement()",
    "window.next(\u0027Vittoria!\u0027)": "window.next(\u0027Vittoria!\u0027)",
    "window.PokeMisteryRL?.Helpers?.modal?.(`": "window.PokeMisteryRL?.Helpers?.modal?.(`",
    "window.rejectRecruitment()": "window.rejectRecruitment()",
    "x1": "x1",
    "x2": "x2",
    "y1": "y1",
    "y2": "y2",
    "Zaino": "Zaino",
    "Zapdos": "Zapdos",
    "Zubat": "Zubat"
  };

  // Per testi con valori variabili, aggiungi qui una regola. Esempio:
  // [/^PIANO (\\d+)$/, "FLOOR $1"]
  const RULES = [
    [/^PIANO (\d+)$/, "PIANO $1"],
    [/^LV (\d+)$/, "LV $1"],
    [/^Ricompensa: \+(\d+)Â¥$/, "Ricompensa: +$1Â¥"]
  ];

  const translate = value => {
    if(typeof value !== "string") return value;
    if(Object.hasOwn(REPLACEMENTS, value)) return REPLACEMENTS[value];
    for(const [pattern, replacement] of RULES){
      if(pattern.test(value)) return value.replace(pattern, replacement);
    }
    return value;
  };

  const applyTo = root => {
    if(!root || root.nodeType === Node.TEXT_NODE){
      if(root?.nodeType === Node.TEXT_NODE){
        const translated = translate(root.nodeValue);
        if(translated !== root.nodeValue) root.nodeValue = translated;
      }
      return;
    }
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const texts = [];
    while(walker.nextNode()) texts.push(walker.currentNode);
    texts.forEach(node => {
      const translated = translate(node.nodeValue);
      if(translated !== node.nodeValue) node.nodeValue = translated;
    });
    root.querySelectorAll?.("[title],[aria-label],[alt],[placeholder]").forEach(element => {
      ["title", "aria-label", "alt", "placeholder"].forEach(attribute => {
        if(element.hasAttribute(attribute)) element.setAttribute(attribute, translate(element.getAttribute(attribute)));
      });
    });
  };

  const observer = new MutationObserver(records => {
    records.forEach(record => {
      if(record.type === "characterData") applyTo(record.target);
      record.addedNodes.forEach(applyTo);
    });
  });
  observer.observe(document.documentElement, {childList:true, subtree:true, characterData:true});
  document.addEventListener("DOMContentLoaded", () => applyTo(document.body));

  /* Guide: tutte le copie sono qui, fuori dal CORE. */
  window.PokeMisteryRL_GuideCopy = {
    it: {
      guide: "GUIDA", choose: "Come si gioca", back: "← INDIETRO",
      basics: "La run", combat: "Combattimento", team: "Squadra", route: "Percorso",
      basicsHint: "Inizia, cresci, raggiungi il boss.",
      combatHint: "Bersagli, turni e mosse.",
      teamHint: "Slot, PS e progressione.",
      routeHint: "Nodi, rifugio e negozio.",
      start: "Inizia la run", startTitle: "Scegli e parti", startText: "Scegli uno starter, poi una coppia di compagni. La selezione resta aperta finché non scegli una carta.",
      levels: "Livelli", levelsTitle: "Crescita durante la run", levelsText: "Ogni KO normale dà +1 livello al Pokémon che lo abbatte. I boss non assegnano livelli.",
      targeting: "Bersagli", targetingTitle: "Ordine degli attacchi", targetingText: "S3 punta il primo nemico libero, S2 il secondo, S1 il terzo. I nemici colpiscono sempre la colonna della formazione più a destra ancora viva: C3, poi C2, infine C1.",
      turns: "Turni", turnsTitle: "Chi agisce per primo", turnsText: "Ogni Pokémon vivo agisce una volta per turno. La Velocità decide l’ordine delle azioni.",
      moves: "Mosse", movesTitle: "Tipo e livello mossa", movesText: "Le mosse hanno tipo e livello. Il Rifugio cambia il tipo una sola volta per nodo; il Dojo può potenziarle.",
      formation: "Formazione", formationTitle: "Ordine della squadra", formationText: "Trascina gli slot della squadra prima del prossimo nodo per scegliere chi occupa S1, S2 e S3. La colonna più a destra viene bersagliata per prima dai nemici.",
      health: "PS e KO", healthTitle: "Proteggi lo Starter", healthText: "A 0 PS un Pokémon è KO e non agisce. In questa run, se lo Starter scelto va KO è game over anche se i compagni sono ancora in piedi. Il Rifugio cura il 50% dei PS all’arrivo.",
      items: "Oggetti", itemsTitle: "Usa lo zaino", itemsText: "Apri lo Zaino dal pulsante nella mappa per controllare e assegnare gli oggetti raccolti alla squadra.",
      nodes: "Nodi", nodesTitle: "Scegli il prossimo passo", nodesText: "Puoi seguire solo i collegamenti illuminati. Arriva al boss per completare il piano.",
      shelter: "Rifugio", shelterTitle: "Cura e cambio mossa", shelterText: "La squadra recupera il 50% dei PS. Puoi cambiare il tipo mossa di un solo Pokémon per quel nodo.",
      shop: "Negozio", shopTitle: "Scaffali e Kecleon", shopText: "Gli scaffali restano uguali quando esci e rientri. Dopo un acquisto si rinnova solo lo slot comprato.",
      events: "Eventi", eventsTitle: "Scelte e sorprese", eventsText: "Un evento può offrire una ricompensa, un aiuto o una sfida. Leggi sempre entrambe le scelte prima di decidere."
    }
  };

  window.PokeMisteryRL_Text = { REPLACEMENTS, RULES, translate, applyTo };
})();

